### ISSUE TITLE
Как с вами связаться? 

### ISSUE THREAD

**Issue by git-admeo** [soulman-is-good/ccnet#2]
Есть вопросы по ccnet, как с вами связаться?

**Comment by soulman-is-good** [comment]
Можно по почте, но вряд ли помогу. Давно не работал с ccnet

5 авг. 2016 г. 19:06 пользователь "git-admeo" notifications@github.com
написал:

Есть вопросы по ccnet, как с вами связаться?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/soulman-is-good/ccnet/issues/2, or mute the thread
